general {
    disable_loading_bar = false
    hide_cursor = true
}

background {
    path = screenshot
    blur_passes = 3
    blur_size = 8
}

input-field {
    size = 250, 50
    outline_thickness = 2

    dots_size = 0.2
    dots_spacing = 0.2

    fade_on_empty = false
    placeholder_text = <i>Password...</i>

    position = 0, -20
    halign = center
    valign = center
}
