general {
    disable_loading_bar = true   # no progress bar
    hide_cursor = true           # hide the mouse
}

background {
    path = solid_black           # black background
}

input-field {
    monitor =
    size = 280, 55
    outline_thickness = 2
    dots_size = .2          
    dots_spacing = 0.2              
    dots_center = true  
    outer_color = rgba(255, 255, 255, 1)
    inner_color = rgba(0, 0, 0, 0)
    font_color = rgba(255, 255, 255, 1)
    fade_on_empty = false
    font_family = "JetBrains Mono Nerd Font"
    placeholder_text = 
    hide_input = false              
    halign = center
    valign = center
    rounding = 0
}
